CREATE TABLE
    FARMTECH_SENSOR_LEITURA (
        ID_LEITURA NUMBER PRIMARY KEY,
        DATA_HORA TIMESTAMP NOT NULL,
        UMIDADE NUMBER (5, 2) NOT NULL,
        TEMPERATURA NUMBER (5, 2) NOT NULL,
        PH NUMBER (4, 2) NOT NULL,
        N NUMBER (1) NOT NULL,
        P NUMBER (1) NOT NULL,
        K NUMBER (1) NOT NULL,
        NIVEL_CHUVA NUMBER (1) NOT NULL,
        STATUS_IRRIGACAO VARCHAR2 (20) NOT NULL,
        SUGESTAO VARCHAR2 (255)
    );

ALTER TABLE FARMTECH_SENSOR_LEITURA ADD CONSTRAINT CK_FARMTECH_N CHECK (N IN (0, 1));

ALTER TABLE FARMTECH_SENSOR_LEITURA ADD CONSTRAINT CK_FARMTECH_P CHECK (P IN (0, 1));

ALTER TABLE FARMTECH_SENSOR_LEITURA ADD CONSTRAINT CK_FARMTECH_K CHECK (K IN (0, 1));

ALTER TABLE FARMTECH_SENSOR_LEITURA ADD CONSTRAINT CK_FARMTECH_NIVEL_CHUVA CHECK (NIVEL_CHUVA IN (0, 1, 2));

ALTER TABLE FARMTECH_SENSOR_LEITURA ADD CONSTRAINT CK_FARMTECH_STATUS_IRRIG CHECK (STATUS_IRRIGACAO IN ('LIGADA', 'DESLIGADA'));