BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FARMTECH_ML_PREVISAO';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE FARMTECH_ML_PREVISAO (
    ID_PREVISAO NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP NOT NULL,
    UMIDADE_ATUAL NUMBER(5,2) NOT NULL,
    TEMPERATURA NUMBER(5,2) NOT NULL,
    PH_ATUAL NUMBER(4,2) NOT NULL,
    N NUMBER(1) NOT NULL,
    P NUMBER(1) NOT NULL,
    K NUMBER(1) NOT NULL,
    NIVEL_CHUVA NUMBER(1) NOT NULL,
    IRRIGACAO_LIGADA NUMBER(1) NOT NULL,
    UMIDADE_PREVISTA NUMBER(5,2),
    PH_PREVISTO NUMBER(4,2),
    PRODUTIVIDADE_ESTIMADA NUMBER(6,2),
    ACAO_RECOMENDADA VARCHAR2(500)
);

ALTER TABLE FARMTECH_ML_PREVISAO ADD CONSTRAINT CK_FARMTECH_ML_N CHECK (N IN (0, 1));
ALTER TABLE FARMTECH_ML_PREVISAO ADD CONSTRAINT CK_FARMTECH_ML_P CHECK (P IN (0, 1));
ALTER TABLE FARMTECH_ML_PREVISAO ADD CONSTRAINT CK_FARMTECH_ML_K CHECK (K IN (0, 1));
ALTER TABLE FARMTECH_ML_PREVISAO ADD CONSTRAINT CK_FARMTECH_ML_CHUVA CHECK (NIVEL_CHUVA IN (0, 1, 2));
ALTER TABLE FARMTECH_ML_PREVISAO ADD CONSTRAINT CK_FARMTECH_ML_IRRIG CHECK (IRRIGACAO_LIGADA IN (0, 1));

COMMIT;
